/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'carId' : bigint,
  'name' : string,
  'preferredDate' : string,
  'bookingTime' : Time,
  'phone' : string,
}
export interface Car {
  'id' : bigint,
  'model' : string,
  'mileage' : bigint,
  'color' : string,
  'year' : bigint,
  'description' : string,
  'transmission' : string,
  'fuelType' : string,
  'brand' : string,
  'price' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'bookTestDrive' : ActorMethod<[string, string, bigint, string], bigint>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllCars' : ActorMethod<[], Array<Car>>,
  'getCarById' : ActorMethod<[bigint], Car>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];