/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Booking = IDL.Record({
  'carId' : IDL.Nat,
  'name' : IDL.Text,
  'preferredDate' : IDL.Text,
  'bookingTime' : Time,
  'phone' : IDL.Text,
});
export const Car = IDL.Record({
  'id' : IDL.Nat,
  'model' : IDL.Text,
  'mileage' : IDL.Nat,
  'color' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'transmission' : IDL.Text,
  'fuelType' : IDL.Text,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'bookTestDrive' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getCarById' : IDL.Func([IDL.Nat], [Car], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'carId' : IDL.Nat,
    'name' : IDL.Text,
    'preferredDate' : IDL.Text,
    'bookingTime' : Time,
    'phone' : IDL.Text,
  });
  const Car = IDL.Record({
    'id' : IDL.Nat,
    'model' : IDL.Text,
    'mileage' : IDL.Nat,
    'color' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'transmission' : IDL.Text,
    'fuelType' : IDL.Text,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'bookTestDrive' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getCarById' : IDL.Func([IDL.Nat], [Car], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };